### ISSUE TITLE
Buttons on the Top Bar Not Working (Qt 6.6.2)

### ISSUE THREAD

**Issue by frchrist** [imitatehappiness/QtCustomTitleBar#2]
![image](https://github.com/user-attachments/assets/a0dd933a-754e-41b4-8cf2-619164b21ad1)
The buttons on the top bar are unresponsive. When clicked, nothing happens. This issue occurs in my application using Qt version 6.6.2.
pls can you help me ?

**Comment by imitatehappiness** [comment]
I am using Qt version 5.15.2 (MinGW 5.3.0)
To begin with, you can check that the button click slots are called.

Also, if you immediately integrated the bar into your application, first check if it works on the basic example.

**Comment by frchrist** [comment]
Ok, it works now. thank you....
